services:
  - type: web
    name: flask-backend
    env: python
    buildCommand: ""
    startCommand: gunicorn backend.app:app
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
    region: oregon